version: "3.8"

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: technical_development
    volumes:
      - technical_mysql_data:/var/lib/mysql
    ports:
       - "3307:3306"
    networks:
      - networks_default

  app:
    env_file: backend/.env
    build:
      context: backend
      dockerfile: dev.dockerfile
    volumes:
      - ./backend:/app
    ports: 
       - "3001:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - networks_default
    environment:
      DATABASE_URL: mysql2://root:password@db/technical_development

  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /usr/src/app
    networks: 
      - networks_default
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev

  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - networks_default
    depends_on:
       - app
       - frontend
volumes:
  technical_mysql_data:
    external: false
networks:
  networks_default:
    name: 'networks_default'
    external: true
    driver: bridge