source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.0"

gem "rails", "~> 7.0.4"
gem "sprockets-rails"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false

gem "mysql2"
gem "figaro"
gem "rack-cors", require: "rack/cors"

gem "rswag-api"
gem "rswag-ui"

gem "bootstrap", "~> 5.2.0"
gem "sassc-rails"
gem "cssbundling-rails"

group :development, :test do
  gem "bundler-audit", require: false
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "factory_bot_rails"
  gem "faker"
  gem "pry"
  gem "pry-byebug"
  gem "rspec-rails"
  gem "rswag-specs"
  gem "rubocop", require: false
end

group :development do
  gem "web-console"
  gem "brakeman"
  gem "spring"
end

group :test do
  gem "simplecov", require: false
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "webmock"
  gem "shoulda-matchers"
end
